---
# bring stack down
# kill loadbalancer
  - hosts: loadbalancer
    become: true
    tasks:
      - service:
           name=nginx
           state=stopped
      - wait_for:
          port=80
          state=drained

# kill webservers
  - hosts: webserver
    become: true
    tasks:
      - service:
          name=apache2
          state=stopped
      - wait_for:
          port=80
          state=stopped

# restart mysql-server
  - hosts: database
    become: true
    tasks:
      - service:
          name=mysql
          state=restarted
      - wait_for:
          host={{ ansible_eth0.ipv4.address }}
          port=3306
          state=started

# bring stack up
# start web server
  - hosts: webserver
    become: true
    tasks:
      - service:
          name=apache2
          state=started
      - wait_for:
          port=80
          state=started


# start load balancer
  - hosts: loadbalancer
    become: true
    tasks:
      - service:
          name=nginx
          state=started
      - wait_for:
          port=80
          state=started
