---
  - hosts: loadbalancer
    become: true
    tasks:
      - name: verify nginx status
        command: service nginx status

  - hosts: webserver
    become: true
    tasks:
      - name: verify apache2 status
        command: service apache2 status

  - hosts: database
    become: true
    tasks:
      - name: verify mysql status
        command: service mysql status
