---
  - hosts: webserver
    become: true
    tasks:
      - name: install_apache2
        apt:
          name={{item}}
          state=present
          update_cache=yes
        with_items:
            - apache2
            - libapache2-mod-wsgi
            - pythin-pip
            - python-virtualenv
